updated the font and made other css changes
KendallDoesCoding/backward-text pull request #22
Opened 2023-03-06 08:48 UTC by Adejuwon-00

updated the font to Nunito Sans and made changes to the header in the HTML and footer in the CSS files

2023-03-06 08:56 UTC, KendallDoesCoding requested changes
I like the fonts you chose but not too fond of the heading (Reverse Text) so can you change the font for that, please?

2023-03-06 17:25 UTC, Adejuwon-00 commented
Sure, I'll do that right away

2023-03-07 05:20 UTC, KendallDoesCoding approved these changes

2023-03-07 05:20 UTC, KendallDoesCoding commented
Thanks for your contribution!

2023-03-07 05:20 UTC, merged