added copy-text button and edited reverse function
KendallDoesCoding/backward-text pull request #5
Opened 2022-09-30 13:16 UTC by HamzaYehia

2022-09-30 14:29 UTC, KendallDoesCoding requested changes
Looks amazing!

But, can you make it so the text the displays reversed is in a color following the color scheme, orange or something?

But, it may have to be changed after #3 gets merged (which I will do)

2022-09-30 16:25 UTC, HamzaYehia commented
> Looks amazing!
> 
> But, can you make it so the text the displays reversed is in a color following the color scheme, orange or something?
> 
> But, it may have to be changed after #3 gets merged (which I will do)

2022-09-30 16:48 UTC, KendallDoesCoding commented
Please make the edits in this branch/PR itself.

2022-09-30 17:03 UTC, HamzaYehia commented
> Please make the edits in this branch/PR itself.
> 

Ok, I'll do it

2022-09-30 17:45 UTC, zabihhaqqani commented
great addition @HamzaYehia!

2022-09-30 17:49 UTC, HamzaYehia commented
> great addition @HamzaYehia!

Thanks!

2022-10-01 09:30 UTC, KendallDoesCoding commented
Just merged #3, can you fix the merge conflicts?

Thanks!

2022-10-01 09:34 UTC, KendallDoesCoding commented
@HamzaYehia Please resolve conflicts.. I just merged #6

2022-10-01 11:41 UTC, HamzaYehia commented
> @HamzaYehia Please resolve conflicts.. I just merged #6

Hi,
I resolved the confilcts and pushed a new commit with copy-text button to the PR.

2022-10-01 16:58 UTC, KendallDoesCoding reviewed
I liked the previous interface, that when the button "reverse" is tapped, the reversed text goes on the next line and the copy button after that, this too is good but can you change it back to that interface, that you made in this PR?

2022-10-02 15:18 UTC, HamzaYehia commented
> I liked the previous interface, that when the button "reverse" is tapped, the reversed text goes on the next line and the copy button after that, this too is good but can you change it back to that interface, that you made in this PR?

I've just changed it back, you can check again now.

2022-10-02 15:33 UTC, HamzaYehia commented
> I liked the previous interface, that when the button "reverse" is tapped, the reversed text goes on the next line and the copy button after that, this too is good but can you change it back to that interface, that you made in this PR?

I've just changed it back, you can check again now.

2022-10-02 15:37 UTC, KendallDoesCoding requested changes
Don't display "Reversed text appears here.." just comment it!

2022-10-02 15:38 UTC, KendallDoesCoding requested changes

2022-10-02 15:38 UTC, KendallDoesCoding commented on index.html
> +      <p id="reversed-text" class="sub-heading"> Reversed text appears here..</p>
```suggestion
      <!--<p id="reversed-text" class="sub-heading"> Reversed text appears here..</p>-->

```

2022-10-02 15:39 UTC, KendallDoesCoding requested changes

2022-10-02 15:39 UTC, KendallDoesCoding commented on index.html
> +      <!--<p id="reversed-text" class="sub-heading"> Reversed text appears here..</p>-->
```suggestion
      <p id="reversed-text" class="sub-heading"> <!--Reversed text appears here..--></p

```

2022-10-02 15:40 UTC, KendallDoesCoding commented on index.html
> +      <p id="reversed-text" class="sub-heading"> <!--Reversed text appears here..--></p
```suggestion
      <p id="reversed-text" class="sub-heading"> <!--Reversed text appears here..--></p>

```

2022-10-02 15:40 UTC, KendallDoesCoding requested changes
oops

2022-10-02 15:41 UTC, KendallDoesCoding approved these changes
Perfect!

2022-10-02 15:42 UTC, merged

2022-10-02 15:42 UTC, KendallDoesCoding commented
Thanks for your contribution @HamzaYehia